# cmake-format configuration for XSigma
# Aligns with .clang-format and project coding standards
# See: https://cmake-format.readthedocs.io/

format:
  # Line width (matches .clang-format ColumnLimit: 100)
  line_width: 100

  # Indentation settings (matches .clang-format IndentWidth: 4)
  indent_width: 2
  tab_size: 2
  use_tabchars: false

  # Formatting behavior
  dangle_parens: true
  separate_ctrl_name_with_space: true
  separate_fn_name_with_space: false

  # Comment handling
  comment_prefix: '  #'
  enable_markup: true

  # Wrapping behavior
  max_subgroups_hwrap: 3
  max_paren_depth: 6

  # Sorting behavior
  enable_sort: true
  autosort: false

# Markup configuration for documentation
markup:
  bullet_char: '*'
  enum_char: '.'
  first_comment_is_literal: false
  literal_comment_pattern: null
  fence_pattern: '^\\s*([`~]{3}[`~]*)(.*)$'
  ruler_pattern: '^\\s*[*]{10,}$'
  explicit_start: null
  explicit_end: null
  implicit_block_start: null
  implicit_block_end: null
  implicit_paragraph_start: null

# Lint configuration (for reference, not used by cmake-format itself)
lint:
  disabled_codes: []
  function_pattern: '[0-9a-z_]+'
  macro_pattern: '[0-9A-Z_]+'
  global_var_pattern: '[A-Z][0-9A-Z_]*'
  internal_var_pattern: '_[A-Z][0-9A-Z_]*'
  local_var_pattern: '[a-z][a-z0-9_]*'
  private_var_pattern: '_[a-z][a-z0-9_]*'
  public_var_pattern: '[A-Z][A-Z0-9_]*'
  argument_var_pattern: '[a-z][a-z0-9_]*'
  keyword_pattern: '[A-Z][A-Z0-9_]*'

