# ============================================================================= XSigma Configuration
# Summary Module
# =============================================================================
# This module provides a function to print a comprehensive summary of the XSigma build
# configuration, including compiler settings, enabled features, and optional dependencies.
# =============================================================================

# Include guard to prevent multiple inclusions
include_guard(GLOBAL)

# Prints accumulated XSigma configuration summary
function(print_configuration_summary)
  message("")
  message("******** Summary ********")
  message("General:")
  message("  CMake version         : ${CMAKE_VERSION}")
  message("  CMake command         : ${CMAKE_COMMAND}")
  message("  System                : ${CMAKE_SYSTEM_NAME}")
  message("  C++ compiler          : ${CMAKE_CXX_COMPILER}")
  message("  C++ compiler id       : ${XSIGMA_COMPILER_ID}")
  message("  C++ compiler version  : ${CMAKE_CXX_COMPILER_VERSION}")
  message("  C++ standard          : ${XSIGMA_CXX_STANDARD}")
  message("  Compiler cache        : ${XSIGMA_CACHE_TYPE}")
  message("  Compiler cache program: ${XSIGMA_CACHE_PROGRAM}")
  message("  CXX flags             : ${CMAKE_CXX_FLAGS}")
  message("  Shared LD flags       : ${CMAKE_SHARED_LINKER_FLAGS}")
  message("  Static LD flags       : ${CMAKE_STATIC_LINKER_FLAGS}")
  message("  Module LD flags       : ${CMAKE_MODULE_LINKER_FLAGS}")
  message("  Build type            : ${CMAKE_BUILD_TYPE}")
  get_directory_property(tmp DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  Compile definitions   : ${tmp}")
  message("  CMAKE_PREFIX_PATH     : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX  : ${CMAKE_INSTALL_PREFIX}")
  message("")
  if(XSIGMA_ENABLE_IWYU)
    message("  IWYU:")
    message("    IWYU executable     : ${XSIGMA_IWYU_EXECUTABLE}")
    message("    IWYU arguments      : ${XSIGMA_IWYU_ARGS}")
  endif()
  get_directory_property(tmp DIRECTORY ${PROJECT_SOURCE_DIR} COMPILE_DEFINITIONS)
  message("  CMake generator       : ${CMAKE_GENERATOR}")
  message("  CMake build tool      : ${CMAKE_BUILD_TOOL}")
  message("  CMake install prefix  : ${CMAKE_INSTALL_PREFIX}")
  message("  CMake build type      : ${CMAKE_BUILD_TYPE}")
  message("  CMake build options   : ${CMAKE_BUILD_OPTIONS}")
  message("  CMake build flags     : ${CMAKE_BUILD_FLAGS}")
  message("  CMAKE_PREFIX_PATH     : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX  : ${CMAKE_INSTALL_PREFIX}")
  message("  XSIGMA_VERSION        : ${XSIGMA_VERSION}")
  message("  BUILD_BINARY          : ${XSIGMA_BINARY_DIR}")
  message("  XSIGMA_DLL_PATHS      : ${XSIGMA_DLL_PATHS}")
  message("  DATA_STORE            : ${XSIGMA_DATA_STORE}")
  message("  XSIGMA_flags:")
  message("    Vectorization       : ${XSIGMA_VECTORIZATION_TYPE}")
  if(XSIGMA_ENABLE_TBB)
    set(_xsigma_smp_backend "TBB")
  else()
    set(_xsigma_smp_backend "STDThread")
  endif()
  message("    USE_GOLD_LINKER     : ${XSIGMA_ENABLE_GOLD_LINKER}")
  message("    Multithreading      : ${_xsigma_smp_backend}")
  message("    Logging backend     : ${XSIGMA_LOGGING_BACKEND}")
  message("    Profiling backend   : ${XSIGMA_PROFILER_TYPE}")
  message("    MKL                 : ${XSIGMA_ENABLE_MKL}")
  message("    Memkind             : ${XSIGMA_ENABLE_MEMKIND}")
  message("    NUMA                : ${XSIGMA_ENABLE_NUMA}")
  message("    Sobol 1111          : ${XSIGMA_SOBOL_1111}")
  message("    LU Pivoting         : ${XSIGMA_LU_PIVOTING}")
  message("    LTO                 : ${XSIGMA_ENABLE_LTO}")
  message("    Magic Enum          : ${XSIGMA_ENABLE_MAGICENUM}")
  message("    Mimalloc            : ${XSIGMA_ENABLE_MIMALLOC}")
  message("    TBB                 : ${XSIGMA_ENABLE_TBB}")
  message("    CUDA                : ${XSIGMA_ENABLE_CUDA}")
  message("    HIP                 : ${XSIGMA_ENABLE_HIP}")
  message("    Documentation       : ${XSIGMA_BUILD_DOCUMENTATION}")
  message("    External libraries  : ${XSIGMA_ENABLE_EXTERNAL}")

  message("  Build:")
  message("    Shared libs         : ${XSIGMA_BUILD_SHARED_LIBS}")
  if(XSIGMA_WRAP_PYTHON OR XSIGMA_BUILD_WHEEL)
    message("  Python:")
    message("    Build wheel         : ${XSIGMA_BUILD_WHEEL}")
    message("    Python version      : ${XSIGMA_PYTHON_VERSION}")
    message("    Python executable   : ${Python3_EXECUTABLE}")
    message("    Python site-packages: ${XSIGMA_PYTHON_SITE_PACKAGES_SUFFIX}")
  else()
    message("  PYTHON                : OFF")
  endif()
  if(XSIGMA_WRAP_JAVA)
    message("  Java:")
    message("    Java version        : ${Java_VERSION_MAJOR}")
    message("    Java executable     : ${Java_JAR_EXECUTABLE}")
    message("    JNI library         : ${XSIGMA_JNI_LIBRARIES}")
    message("    JNI includes        : ${XSIGMA_JNI_INCLUDE_DIRS}")
  else()
    message("  JAVA                  : OFF")
  endif()
  if(XSIGMA_ENABLE_CUDA)
    message("  CUDA:")
    message("    CUDA include path   : ${CUDA_INCLUDE_DIRS}")
    message("    NVCC executable     : ${CUDA_NVCC_EXECUTABLE}")
    message("    NVCC flags          : ${CMAKE_CUDA_FLAGS}")
    message("    CUDA host compiler  : ${CUDA_HOST_COMPILER}")
    message("    NVCC --device-c     : ${CUDA_SEPARABLE_COMPILATION}")
    message("    CUDA version        : ${CUDA_VERSION}")
    message("    CUDA library        : ${XSIGMA_CUDA_LIBRARIES}")
    message("    CUDA compiler       : ${CMAKE_CUDA_COMPILER}")
    message("    CUDA includes       : ${CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES}")
  else()
    message("  CUDA                  : OFF")
  endif()
  if(XSIGMA_BUILD_TESTING)
    message("  Testing:")
    message("    Google test         : ${XSIGMA_ENABLE_GTEST}")
    message("    Benchmark           : ${XSIGMA_ENABLE_BENCHMARK}")
    message("    Valgrind            : ${XSIGMA_ENABLE_VALGRIND}")
    message("    Coverage            : ${XSIGMA_ENABLE_COVERAGE}")
    message("    IWYU                : ${XSIGMA_ENABLE_IWYU}")
    message("    Clang-tidy          : ${XSIGMA_ENABLE_CLANGTIDY}")
    message("    Clang-tidy fix      : ${XSIGMA_ENABLE_FIX}")
    message("    Cppcheck            : ${XSIGMA_ENABLE_CPPCHECK}")
    if(XSIGMA_ENABLE_SANITIZER)
      message("    Sanitizer           : ${XSIGMA_SANITIZER_TYPE}")
    endif()
  endif()

  message("")
endfunction()
